### ISSUE TITLE
ERROR! ansible-vault requires either the cryptography library (preferred) or pycrypto in order to function.

### ISSUE THREAD

**Issue by hkirsman** [pad92/docker-ansible-alpine#2]
Tried to run this

     docker run -it --rm -v ${PWD}:/ansible pad92/ansible-alpine:latest ansible-vault encrypt_string

But got error

    ERROR! ansible-vault requires either the cryptography library (preferred) or pycrypto in order to function.

**Comment by pad92** [comment]
package added
thx for your feedback
