### ISSUE TITLE
What does mitogen do

### ISSUE THREAD

**Issue by zhangguanzhang** [pad92/docker-ansible-alpine#3]
What does `mitogen` do
```
curl -s -L https://networkgenomics.com/try/mitogen-${MITOGEN_VERSION}.tar.gz | tar xzf - -C /opt/ \
 && mv /opt/mitogen-* /opt/mitogen
```

**Comment by pad92** [comment]
Hello,

Mitogen for Ansible is a completely redesigned UNIX connection layer and module runtime for Ansible. Requiring minimal configuration changes, it updates Ansible’s slow and wasteful shell-centric implementation with pure-Python equivalents, invoked via highly efficient remote procedure calls to persistent interpreters tunnelled over SSH. No changes are required to target hosts.

The extension is considered stable and real-world use is encouraged.

https://mitogen.networkgenomics.com/ansible_detailed.html
